### PR TITLE
Allow file to be regex + output JSON info about the asset + bug fix

### LINKED ISSUE #6: Allow file to be regex
Hi,
It would be great if the filename could be a regex, in case it isn't know in advance. Additionally, outputting `browser_download_url` could be useful in some case

### LINKED ISSUE #17: The `set-output` command is deprecated and will be disabled soon
There is a warning : 
```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

It is caused by `@actions/core` not being the latest version (`1.10.0`, currently `1.9.1`), normally dependabot would have taken care of it, is it not enabled for version updates?

### PR DESCRIPTION
**Pull request by koplo199**
Fix #6
Additionally, it fix a bug where if the `created_at` value of two releases are the same (happens if the build is done on another repository), the alphabetical order was used instead of the `published_at` value, resulting in choosing the wrong latest release. It now uses correctly the `published_at` value.

Also fix #17

### CODE REVIEW

**Comment by koplo199** [comment]
@madrobot You're absolutely right for the commits name, I'm sorry. 

In the last two commits I allowed `prefix` to be explicitly set to empty string (useful for targeting all tags), and made changes to pass the CI

**Comment by koplo199** [comment]
@madrobot Ok I'm done modifying stuff. By the way, I see that it generated a lot of change in the `dist` directory, do you want me to delete change made in `dist` so you can regenerate it yourself?

**Comment by wmxscott** [comment]
@koplo199 looking good. Take care of my outstanding notes and I'll merge. Lines #45 and #79

**Comment by koplo199** [comment]
@madrobot Which notes? I cannot see them :'(
(But I have no doubt they're indeed outstanding)

**Comment by koplo199** [comment]
Ok, dependencies are now up to date :tada: 
But I still can't see your notes :(

**Comment by koplo199** [comment]
By the way I still can't see your notes, but I tried to guess the required change in my last commit :')

**Comment by wmxscott** [comment]
There are way too many changes now in this PR. I suggest you fork the repo into your own organization and make the changes you see fit. Thanks.

**Comment by koplo199** [comment]
@madrobot Whaaaat? Most changes are just dependencies update to fix issues like #17 and are directly merged from dependabot PR's, I really don't understand your reaction. Virtually nothing changed since you gave your last 'go'...

**Comment by koplo199** [comment]
@madrobot ?

**Pull request closed without merging**
